kind: Deployment
apiVersion: apps/v1
metadata:
  name: nexus
  namespace: management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:3.11.0
        ports:
        - containerPort: 8081
        - containerPort: 5000
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
          subPath: nexus
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: tool-persistent-volume-claim
---
  kind: Service
  apiVersion: v1
  metadata:
    name: nexus
    namespace: management
  spec:
    type: LoadBalancer
    ports:
    - name: http
      port: 80
      targetPort: 8081
    - name: docker
      port: 5000
      targetPort: 5000
    selector:
      app: nexus
