kind: Deployment
apiVersion: apps/v1
metadata:
  name: sonarqube
  namespace: management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:7.1-alpine
        ports:
        - containerPort: 9000
        - containerPort: 9092
        volumeMounts:
        - name: sonarqube-volume
          mountPath: /opt/sonarqube/data
          subPath: sonarqube/data
        - name: sonarqube-volume
          mountPath: /opt/sonarqube/extensions
          subPath: sonarqube/extensions
      volumes:
      - name: sonarqube-volume
        persistentVolumeClaim:
          claimName: tool-persistent-volume-claim
---
kind: Service
apiVersion: v1
metadata:
  name: sonarqube
  namespace: management
spec:
  type: LoadBalancer
  ports:
  - name: sonarqube-server
    port: 9000
    targetPort: 9000
  - name: sonarqube-embedded-db
    port: 9092
    targetPort: 9092
  selector:
    app: sonarqube
