kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tool-persistent-volume-claim
  namespace: management
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
