kind: PersistentVolume
apiVersion: v1
metadata:
  name: host-persistent-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/Users/bmericle/mnt"
