kind: Service
apiVersion: v1
metadata:
  name: jenkins
spec:
  type: LoadBalancer
  ports:
  - name: jenkins-master
    port: 8080
    targetPort: 8080
  - name: jenkins-agent
    port: 50000
    targetPort: 50000
  selector:
    app: jenkins
