kind: Service
apiVersion: v1
metadata:
  name: nexus
spec:
  type: LoadBalancer
  ports:
  - name: nexus
    port: 8081
    targetPort: 8081
  - name: nexus-docker-repo-port
    port: 18444
    targetPort: 18444
  selector:
    app: nexus
