kind: Service
apiVersion: v1
metadata:
  name: sonarqube
spec:
  type: LoadBalancer
  ports:
  - name: sonarqube-server
    port: 9000
    targetPort: 9000
  - name: sonarqube-embedded-db
    port: 9092
    targetPort: 9092
  selector:
    app: sonarqube
