kind: Deployment
apiVersion: apps/v1
metadata:
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3:3.11.0
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
          subPath: nexus
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: tool-persistent-volume-claim
