kind: Deployment
apiVersion: apps/v1
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:7.1-alpine
        ports:
        - containerPort: 9000
        - containerPort: 9092
        volumeMounts:
        - name: sonarqube-volume
          mountPath: /opt/sonarqube/data
          subPath: sonarqube/data
        - name: sonarqube-volume
          mountPath: /opt/sonarqube/extensions
          subPath: sonarqube/extensions
      volumes:
      - name: sonarqube-volume
        persistentVolumeClaim:
          claimName: tool-persistent-volume-claim
