kind: Deployment
apiVersion: apps/v1
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:7.1-alpine
        ports:
        - containerPort: 9000
        - containerPort: 9092
        volumeMounts:
        - name: sonarqube-data
          mountPath: /var/sonarqube_data
      volumes:
        - name: sonarqube-data
          emptyDir: {}
