kind: Deployment
apiVersion: apps/v1
metadata:
  name: jenkins
  namespace: management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: bpmericle/jenkins-with-plugins:2.120.2
        env:
        - name: JAVA_OPTS
          value: -Djenkins.install.runSetupWizard=false
        - name: NEXUS_HOSTNAME
          value: nexus.crosslaketech.com
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: docker-sock-volume
          mountPath: /var/run/docker.sock
        - name: jenkins-home
          mountPath: /var/jenkins_home
          subPath: jenkins
      volumes:
      - name: docker-sock-volume
        hostPath:
          path: /var/run/docker.sock
          type: File
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: tool-persistent-volume-claim
---
kind: Service
apiVersion: v1
metadata:
  name: jenkins
  namespace: management
spec:
  type: LoadBalancer
  ports:
  - name: jenkins-master
    port: 8086
    targetPort: 8080
  - name: jenkins-agent
    port: 50000
    targetPort: 50000
  selector:
    app: jenkins
